"use strict";
const c=document.getElementById('game'),ctx=c.getContext('2d'),$=s=>document.querySelector(s);
const COLORS=['#ef334d','#8b3de0','#ff8d18','#19b970','#2588ea','#13c5c7'];
const DARK=['#ad1529','#562090','#b85a08','#0c7547','#1555a7','#087c80'];
const DIRS=[{dx:0,dy:-1,ch:'↑'},{dx:1,dy:0,ch:'→'},{dx:0,dy:1,ch:'↓'},{dx:-1,dy:0,ch:'←'}];
const S={level:+localStorage.dyr_level||1,speed:1,blocks:[],shots:[],fx:[],clouds:[],cleared:0,target:18,lives:3,yarn:18,spools:[0,0,0,0],caps:[5,5,5,5],hammer:3,shuffle:2,rainbow:2,running:true,last:performance.now(),time:0,dragon:{x:.18,dir:1,state:'fly',timer:3.6,phase:0,drop:null,blink:0,mouth:0},layout:{}};
function W(){return c.clientWidth} function H(){return c.clientHeight}
function resize(){const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);layout();if(!S.blocks.length)reset()} addEventListener('resize',resize);
function layout(){const w=W(),h=H(),dock=Math.max(105,document.querySelector('.dock').offsetHeight||112);S.layout={w,h,dock,scene:h*.40,barTop:h*.405,boardTop:h*.505,boardBottom:h-dock-12,cannonY:h*.485};}
function rand(n){return Math.floor(Math.random()*n)}
function reset(){layout();S.blocks=[];S.shots=[];S.fx=[];S.cleared=0;S.target=Math.min(42,16+S.level*2);S.lives=3;S.yarn=S.target;S.spools=[0,0,0,0];S.caps=[5,5,5,5].map(v=>v+Math.floor(S.level/7));S.running=true;S.hammer=3;S.shuffle=2;S.rainbow=2;Object.assign(S.dragon,{x:.18,dir:1,state:'fly',timer:3.8,phase:0,drop:null,mouth:0});makeBoard();hud();hide()}
function makeBoard(){const L=S.layout,cols=7,rows=Math.min(8,5+Math.floor(S.level/3)),cellW=(L.w-24)/cols,cellH=(L.boardBottom-L.boardTop)/rows,bw=Math.min(48,cellW-3),bh=Math.min(35,cellH-3);let id=0;for(let r=0;r<rows;r++)for(let q=0;q<cols;q++){if(Math.random()<.28&&r>0)continue;const locked=r<2&&Math.random()<Math.min(.28,S.level*.02);S.blocks.push({id:id++,x:12+cellW*(q+.5),y:L.boardTop+cellH*(r+.5),w:bw,h:bh,color:rand(4),dir:rand(4),locked,need:locked?1+rand(3):0,dead:false,shake:0,scale:1,vy:0,landing:0})}while(S.blocks.length<S.target+8)addRandomBlock(false)}
function addRandomBlock(falling=true){const L=S.layout,cols=7,cellW=(L.w-24)/cols,q=rand(cols),bw=Math.min(48,cellW-3),targetY=L.boardTop+18+rand(Math.max(1,Math.floor((L.boardBottom-L.boardTop-40)/38)))*38;S.blocks.push({id:Date.now()+Math.random(),x:12+cellW*(q+.5),y:falling?L.boardTop-50:targetY,targetY,w:bw,h:33,color:rand(4),dir:rand(4),locked:false,need:0,dead:false,shake:0,scale:falling?.2:1,vy:falling?110:0,landing:falling?1:0})}
function hud(){$('#level').textContent='Level '+S.level;$('#progress').textContent=Math.round(S.cleared/S.target*100)+' %';$('#hammerN').textContent=S.hammer;$('#shuffleN').textContent=S.shuffle;$('#rainbowN').textContent=S.rainbow;$('#spools').innerHTML=S.spools.map((n,i)=>`<div class="spool"><div class="reel"><div class="thread" style="background:${COLORS[i]}"></div></div><span>${n}/${S.caps[i]}</span></div>`).join('')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),900)}
function clearPath(b){const d=DIRS[b.dir];for(const o of S.blocks){if(o.dead||o===b||o.landing)continue;const ax=Math.abs(o.x-b.x),ay=Math.abs(o.y-b.y);if(d.dx&&ay<(b.h+o.h)*.43&&Math.sign(o.x-b.x)===d.dx&&ax<W()*.42)return false;if(d.dy&&ax<(b.w+o.w)*.43&&Math.sign(o.y-b.y)===d.dy&&ay<H()*.40)return false}return true}
function shootBlock(b,force=false){if(!S.running||b.dead||b.landing)return;if(b.locked&&!force){b.shake=.35;toast('🔒 Noch '+b.need+' Zug'+(b.need>1?'e':'')+' nötig');return}if(!force&&!clearPath(b)){b.shake=.35;toast('Pfeilweg blockiert');return}if(!force&&S.spools[b.color]>=S.caps[b.color]){b.shake=.35;toast('Diese Spule ist voll');return}const d=DIRS[b.dir],distance=Math.max(W(),H())*.7;S.shots.push({x:b.x,y:b.y,sx:b.x,sy:b.y,tx:b.x+d.dx*distance,ty:b.y+d.dy*distance,t:0,color:b.color,block:b,force});b.dead=true}
function finishShot(s){const b=s.block;S.cleared++;if(!s.force)S.spools[b.color]++;S.yarn=Math.max(0,S.yarn-1);burst(s.x,s.y,COLORS[b.color],15);for(const q of S.blocks)if(!q.dead&&q.locked){q.need--;if(q.need<=0){q.locked=false;burst(q.x,q.y,'#ffd52d',10)}}hud();if(S.cleared>=S.target)win()}
function burst(px,py,col,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=35+Math.random()*130;S.fx.push({x:px,y:py,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.55+Math.random()*.45,col,size:3+Math.random()*4})}}
function dragonLogic(dt){const d=S.dragon,L=S.layout;d.phase+=dt*S.speed;d.blink=Math.random()<.008?1:Math.max(0,d.blink-dt*9);if(d.state==='fly'){d.x+=d.dir*dt*(.11+S.level*.002)*S.speed;if(d.x>.82)d.dir=-1;if(d.x<.18)d.dir=1;d.timer-=dt*S.speed;if(d.timer<=0){d.state='descend';d.mouth=1;d.drop={color:rand(4),dir:rand(4)};d.timer=0}}else if(d.state==='descend'){d.timer+=dt*S.speed;if(d.timer>.7){d.state='release';d.timer=0;addRandomBlock(true);burst(d.x*L.w,120,'#ffd23c',8)}}else if(d.state==='release'){d.timer+=dt*S.speed;if(d.timer>.45){d.state='ascend';d.timer=0;d.drop=null}}else if(d.state==='ascend'){d.timer+=dt*S.speed;if(d.timer>.7){d.state='fly';d.timer=Math.max(1.8,4.4-S.level*.08);d.mouth=0}}}
function update(dt){S.time+=dt;for(const b of S.blocks){b.shake=Math.max(0,b.shake-dt);if(b.landing){b.y+=b.vy*dt*S.speed;b.vy+=260*dt*S.speed;b.scale=Math.min(1,b.scale+dt*2.5);if(b.y>=b.targetY){b.y=b.targetY;b.landing=0;b.scale=1;burst(b.x,b.y,'#ffffff',7)}}}if(!S.running)return;dragonLogic(dt);for(const s of S.shots){s.t+=dt*4.4*S.speed;const t=Math.min(1,s.t),e=1-Math.pow(1-t,3);s.x=s.sx+(s.tx-s.sx)*e;s.y=s.sy+(s.ty-s.sy)*e;if(t>=1&&!s.done){s.done=true;finishShot(s)}}S.shots=S.shots.filter(s=>!s.done);for(const p of S.fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=150*dt;p.life-=dt}S.fx=S.fx.filter(p=>p.life>0);const active=S.blocks.filter(b=>!b.dead).length;if(active>S.target-S.cleared+18){S.lives--;toast('Zu viele Steine! ❤️ '+S.lives);S.blocks.splice(S.blocks.findIndex(b=>!b.dead),1);if(S.lives<=0)lose()}}
function rr(cx,cy,w,h,r){ctx.beginPath();ctx.roundRect(cx-w/2,cy-h/2,w,h,r)}
function background(){const L=S.layout;let g=ctx.createLinearGradient(0,0,0,L.scene);g.addColorStop(0,'#62dff1');g.addColorStop(1,'#a6edf4');ctx.fillStyle=g;ctx.fillRect(0,0,L.w,L.scene);ctx.fillStyle='#dff6f0';ctx.fillRect(0,L.scene,L.w,L.barTop-L.scene);ctx.fillStyle='#f1f2f4';ctx.fillRect(0,L.barTop,L.w,L.h-L.barTop);ctx.globalAlpha=.17;ctx.strokeStyle='#fff';ctx.lineWidth=1;for(let i=0;i<18;i++){ctx.beginPath();ctx.arc((i*77+S.time*12)%L.w,35+(i*43)%(L.scene-50),8+i%7,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;ctx.fillStyle='#9ddf8a';ctx.beginPath();ctx.moveTo(0,L.scene);for(let q=0;q<=L.w;q+=30)ctx.lineTo(q,L.scene-18-Math.sin(q*.045)*14);ctx.lineTo(L.w,L.scene);ctx.fill()}
function yarnTrack(){const L=S.layout,pts=[];for(let i=0;i<=44;i++){const t=i/44,ang=t*Math.PI*2.15+.4,rad=(.42-.22*t)*Math.min(L.w,L.scene);pts.push([L.w*.5+Math.cos(ang)*rad,L.scene*.56+Math.sin(ang)*rad*.54])}ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=24;ctx.strokeStyle='#e3e8e7';ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();const remain=Math.max(0,S.yarn),ratio=remain/Math.max(1,S.target);const count=Math.ceil(44*ratio);for(let i=0;i<count;i++){ctx.strokeStyle=COLORS[Math.floor(i/5)%4];ctx.lineWidth=19;ctx.beginPath();ctx.moveTo(...pts[i]);ctx.lineTo(...pts[i+1]);ctx.stroke();ctx.strokeStyle='#ffffff35';ctx.lineWidth=3;ctx.stroke()}ctx.textAlign='center';ctx.font='34px serif';ctx.fillText('🐱',L.w*.5,L.scene*.56+12);ctx.font='21px serif';ctx.fillText('❤️'.repeat(Math.max(0,S.lives)),L.w*.5,L.scene*.43);ctx.font='25px serif';ctx.fillText('🎁',L.w-39,L.scene*.72);ctx.fillText('🍪',45,L.scene*.72)}
function drawDragon(){const d=S.dragon,L=S.layout;let y=82+Math.sin(d.phase*3)*6;if(d.state==='descend')y+=Math.min(1,d.timer/.7)*54;if(d.state==='release')y+=54;if(d.state==='ascend')y+=54*(1-Math.min(1,d.timer/.7));const px=d.x*L.w,flip=d.dir<0?-1:1,flap=Math.sin(d.phase*13)*.55;ctx.save();ctx.translate(px,y);ctx.scale(flip,1);ctx.rotate(Math.sin(d.phase*2)*.035);ctx.strokeStyle='#6b351f';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-31,8);ctx.quadraticCurveTo(-53,24+Math.sin(d.phase*5)*7,-67,12);ctx.stroke();ctx.fillStyle='#7a39d3';ctx.save();ctx.translate(-17,-6);ctx.rotate(-.35-flap*.35);ctx.beginPath();ctx.ellipse(-15,-13,26,11,-.2,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(8,-7);ctx.rotate(.35+flap*.35);ctx.beginPath();ctx.ellipse(17,-14,27,11,.2,0,Math.PI*2);ctx.fill();ctx.restore();ctx.fillStyle='#ee6b24';ctx.beginPath();ctx.ellipse(0,4,34,25,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffad27';ctx.beginPath();ctx.ellipse(17,-14,22,19,.1,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(25,-19,6,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#222';if(!d.blink){ctx.beginPath();ctx.arc(27,-19,2.6,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#f5d64a';for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(-20+i*12,-19);ctx.lineTo(-15+i*12,-34-(i%2)*3);ctx.lineTo(-8+i*12,-18);ctx.fill()}ctx.strokeStyle='#7e361f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(29,-6);ctx.quadraticCurveTo(37,-2,35,5+d.mouth*5);ctx.stroke();ctx.fillStyle='#fef2cf';ctx.beginPath();ctx.ellipse(-2,12,17,11,0,0,Math.PI*2);ctx.fill();if(d.drop){ctx.strokeStyle='#553524';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(5,25);ctx.lineTo(5,49);ctx.stroke();ctx.save();ctx.translate(5,56);ctx.fillStyle=COLORS[d.drop.color];rr(0,0,31,24,6);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(DIRS[d.drop.dir].ch,0,1);ctx.restore()}ctx.restore()}
function drawBar(){const L=S.layout;ctx.fillStyle='#e4d6dc';ctx.fillRect(0,L.barTop,L.w,L.boardTop-L.barTop);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(0,L.barTop,L.w,L.boardTop-L.barTop);ctx.fillStyle='#bd8f9e';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText('FARBSPEICHER',L.w/2,L.barTop+15);for(let i=0;i<4;i++){const bx=14+i*(L.w-28)/4,bw=(L.w-28)/4-6;ctx.fillStyle='#c8b1ba';rr(bx+bw/2,L.barTop+38,bw,29,7);ctx.fill();if(S.spools[i]){ctx.fillStyle=COLORS[i];rr(bx+bw/2,L.barTop+38,bw-8,18,5);ctx.fill()}}}
function block(b){if(b.dead)return;const sh=b.shake?Math.sin(b.shake*70)*6:0;ctx.save();ctx.translate(b.x+sh,b.y);ctx.scale(b.scale,b.scale);ctx.shadowColor='#0005';ctx.shadowBlur=5;ctx.shadowOffsetY=3;let g=ctx.createLinearGradient(0,-b.h/2,0,b.h/2);g.addColorStop(0,COLORS[b.color]);g.addColorStop(1,DARK[b.color]);ctx.fillStyle=b.locked?'#24272d':g;rr(0,0,b.w,b.h,7);ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='#ffffff99';ctx.stroke();ctx.shadowColor='transparent';ctx.fillStyle='#fff';ctx.font='900 23px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(b.locked?'🔒'+Math.max(0,b.need):DIRS[b.dir].ch,0,1);ctx.restore()}
function cannon(){const L=S.layout,py=L.cannonY;ctx.save();ctx.translate(L.w/2,py);ctx.fillStyle='#454b5d';rr(0,0,43,42,8);ctx.fill();ctx.fillStyle='#737d91';ctx.fillRect(-8,-27,16,28);ctx.fillStyle='#ffd43d';ctx.beginPath();ctx.arc(0,-29,8,0,Math.PI*2);ctx.fill();ctx.restore()}
function draw(){const L=S.layout;ctx.clearRect(0,0,L.w,L.h);background();yarnTrack();drawDragon();drawBar();cannon();for(const b of S.blocks)block(b);for(const s of S.shots){ctx.strokeStyle=COLORS[s.color]+'66';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(s.sx,s.sy);ctx.lineTo(s.x,s.y);ctx.stroke();ctx.fillStyle=COLORS[s.color];rr(s.x,s.y,22,16,4);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 13px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(DIRS[s.block.dir].ch,s.x,s.y)}for(const p of S.fx){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.col;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;ctx.fillStyle='#627684';ctx.font='bold 12px system-ui';ctx.textAlign='left';ctx.fillText('Ziel '+S.cleared+'/'+S.target,10,L.boardBottom+8);ctx.textAlign='right';ctx.fillText('Drache '+Math.ceil(Math.max(0,S.dragon.timer))+'s',L.w-10,L.boardBottom+8)}
function loop(t){const dt=Math.min(.033,(t-S.last)/1000);S.last=t;update(dt);draw();requestAnimationFrame(loop)}
function pos(e){const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
c.addEventListener('pointerdown',e=>{e.preventDefault();const p=pos(e);const hit=S.blocks.filter(b=>!b.dead&&!b.landing&&Math.abs(p.x-b.x)<b.w*.7&&Math.abs(p.y-b.y)<b.h*.75).sort((a,b)=>Math.hypot(p.x-a.x,p.y-a.y)-Math.hypot(p.x-b.x,p.y-b.y))[0];if(hit)shootBlock(hit)});
$('#hammer').onclick=()=>{if(!S.running||S.hammer<=0)return;const b=S.blocks.filter(b=>!b.dead&&!b.landing).sort((a,b)=>b.y-a.y)[0];if(b){S.hammer--;shootBlock(b,true);hud()}};
$('#shuffle').onclick=()=>{if(!S.running||S.shuffle<=0)return;S.shuffle--;const alive=S.blocks.filter(b=>!b.dead&&!b.landing),places=alive.map(b=>[b.x,b.y]).sort(()=>Math.random()-.5);alive.forEach((b,i)=>{[b.x,b.y]=places[i];b.dir=rand(4)});hud();toast('Steine gemischt')};
$('#rainbow').onclick=()=>{if(!S.running||S.rainbow<=0)return;S.rainbow--;for(let i=0;i<4;i++){const b=S.blocks.find(b=>!b.dead&&!b.landing&&b.color===i);if(b)shootBlock(b,true)}hud()};
$('#speed').onclick=()=>{S.speed=S.speed===1?2:1;$('#speed').textContent='⏩ x'+S.speed};
$('#settings').onclick=()=>{S.running=false;show('Spielanleitung',`<div class="help"><p><b>Ziel:</b> Entferne die Garnstrecke und rette die Katze.</p><p>Tippe einen Pfeilstein an. Er fliegt nur in Pfeilrichtung, wenn kein anderer Stein im Weg ist.</p><p>Der animierte Drache fliegt, sinkt ab und bringt regelmäßig einen neuen farbigen Stein.</p><p>🔨 zerstört einen Stein, 🔀 mischt das Feld, 🌈 entfernt mehrere Farben.</p></div><button class="action" id="restart">Level neu starten</button>`)};
$('#close').onclick=()=>{hide();S.running=true};document.addEventListener('click',e=>{if(e.target.id==='restart')reset();if(e.target.id==='next'){S.level++;localStorage.dyr_level=S.level;reset()}if(e.target.id==='retry')reset()});
function show(t,b){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modal').classList.remove('hidden')}function hide(){$('#modal').classList.add('hidden')}
function win(){S.running=false;localStorage.dyr_level=S.level+1;show('Level geschafft!',`<div class="big">🎉🐱🐉</div><p>Die Katze ist gerettet.</p><button class="action" id="next">Nächstes Level</button>`)}function lose(){S.running=false;show('Level verloren',`<div class="big">💥</div><p>Das Spielfeld ist überfüllt.</p><button class="action" id="retry">Noch einmal</button>`)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});resize();requestAnimationFrame(t=>{S.last=t;requestAnimationFrame(loop)});
