"use strict";
const c=document.getElementById('game'),x=c.getContext('2d'),$=s=>document.querySelector(s);
const COLORS=['#ef3949','#8a42de','#ff9224','#20b777','#2389e8','#19c7c8'];
const DARK=['#a51524','#54208f','#b95a0b','#0d7450','#1555a6','#087c80'];
const DIRS=[{dx:0,dy:-1,ch:'↑'},{dx:1,dy:0,ch:'→'},{dx:0,dy:1,ch:'↓'},{dx:-1,dy:0,ch:'←'}];
const S={level:+localStorage.dyr_level||1,speed:1,blocks:[],shots:[],fx:[],dragonX:70,dragonDir:1,dragonDrop:2.6,cleared:0,target:16,lives:3,yarn:20,spools:[0,0,0,0],caps:[4,4,4,4],hammer:3,shuffle:2,rainbow:2,running:true,last:performance.now(),shake:0,flash:0};
function W(){return c.clientWidth} function H(){return c.clientHeight}
function resize(){const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);x.setTransform(d,0,0,d,0,0)} addEventListener('resize',resize);
function rng(n){const v=Math.sin(n*999.13+S.level*77.7)*43758.5;return v-Math.floor(v)}
function rand(n){return Math.floor(Math.random()*n)}
function reset(){S.blocks=[];S.shots=[];S.fx=[];S.cleared=0;S.target=Math.min(34,14+S.level*2);S.lives=3;S.yarn=S.target;S.spools=[0,0,0,0];S.caps=[4,4,4,4].map(v=>v+Math.floor(S.level/6));S.dragonDrop=2.2;S.running=true;S.hammer=3;S.shuffle=2;S.rainbow=2;makeBoard();hud();hide();}
function makeBoard(){const w=W(),top=H()*.49,bottom=H()-35,cols=7,rows=Math.min(7,4+Math.floor(S.level/2)),bw=Math.min(46,(w-42)/cols),bh=34;let id=0;for(let r=0;r<rows;r++)for(let q=0;q<cols;q++){if(Math.random()<.2&&r>0)continue;const col=rand(4),dir=rand(4),locked=(r<2&&Math.random()<Math.min(.32,S.level*.025));S.blocks.push({id:id++,x:21+q*((w-42)/cols)+(bw/2),y:top+r*((bottom-top-20)/rows)+bh/2,w:bw-4,h:bh,color:col,dir,locked,need:locked?1+rand(3):0,dead:false,shake:0});}while(S.blocks.length<S.target+5){const q=rand(cols),r=rand(rows);S.blocks.push({id:id++,x:21+q*((w-42)/cols)+bw/2,y:top+r*((bottom-top-20)/rows)+bh/2,w:bw-4,h:bh,color:rand(4),dir:rand(4),locked:false,need:0,dead:false,shake:0});}}
function hud(){$('#level').textContent='Level '+S.level;$('#progress').textContent=Math.round(S.cleared/S.target*100)+' %';$('#hammerN').textContent=S.hammer;$('#shuffleN').textContent=S.shuffle;$('#rainbowN').textContent=S.rainbow;$('#spools').innerHTML=S.spools.map((n,i)=>`<div class="spool"><div class="thread" style="background:${COLORS[i]}"></div><span>${n}/${S.caps[i]}</span></div>`).join('')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),850)}
function clearPath(b){const d=DIRS[b.dir];for(const o of S.blocks){if(o.dead||o===b)continue;const ax=Math.abs(o.x-b.x),ay=Math.abs(o.y-b.y);if(d.dx!==0&&ay<(b.h+o.h)*.43&&Math.sign(o.x-b.x)===d.dx&&ax<W()*.35)return false;if(d.dy!==0&&ax<(b.w+o.w)*.43&&Math.sign(o.y-b.y)===d.dy&&ay<H()*.32)return false;}return true}
function shootBlock(b,force=false){if(!S.running||b.dead)return;if(b.locked&&!force){b.shake=.35;toast('🔒 Erst '+b.need+' Stein'+(b.need>1?'e':'')+' entfernen');return}if(!force&&!clearPath(b)){b.shake=.35;toast('Weg blockiert');return}if(!force&&S.spools[b.color]>=S.caps[b.color]){b.shake=.35;toast('Spule voll – andere Farbe zuerst');return}const sx=W()/2,sy=H()*.46;S.shots.push({x:sx,y:sy,tx:b.x,ty:b.y,t:0,color:b.color,block:b,force});b.dead=true;}
function finishShot(s){const b=s.block;S.cleared++;if(!s.force)S.spools[b.color]++;S.yarn=Math.max(0,S.yarn-1);burst(b.x,b.y,COLORS[b.color]);for(const q of S.blocks)if(!q.dead&&q.locked){q.need--;if(q.need<=0){q.locked=false;burst(q.x,q.y,'#ffd02c',8)}}hud();if(S.cleared>=S.target)win();}
function burst(px,py,col,n=13){for(let i=0;i<n;i++){const a=Math.random()*6.28,v=35+Math.random()*120;S.fx.push({x:px,y:py,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.6+Math.random()*.4,col})}}
function dragonDrop(){const alive=S.blocks.filter(b=>!b.dead);if(alive.length>S.target-S.cleared+11){S.lives--;toast('🐉 Zu viele Steine! ❤️ '+S.lives);if(S.lives<=0)lose();return}const cols=7,q=rand(cols),top=H()*.51,bw=Math.min(46,(W()-42)/cols);S.blocks.push({id:Date.now(),x:21+q*((W()-42)/cols)+bw/2,y:top,w:bw-4,h:34,color:rand(4),dir:rand(4),locked:false,need:0,dead:false,shake:0});}
function update(dt){if(!S.running)return;S.dragonX+=S.dragonDir*(55+S.level*2)*dt*S.speed;if(S.dragonX>W()-65)S.dragonDir=-1;if(S.dragonX<65)S.dragonDir=1;S.dragonDrop-=dt*S.speed;if(S.dragonDrop<=0){dragonDrop();S.dragonDrop=Math.max(1.5,3.4-S.level*.07)}for(const b of S.blocks)b.shake=Math.max(0,b.shake-dt);for(const s of S.shots){s.t+=dt*4*S.speed;const t=Math.min(1,s.t),e=1-Math.pow(1-t,3);s.x=(W()/2)+(s.tx-W()/2)*e;s.y=(H()*.46)+(s.ty-H()*.46)*e;if(t>=1&&!s.done){s.done=true;finishShot(s)}}S.shots=S.shots.filter(s=>!s.done);for(const p of S.fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=140*dt;p.life-=dt}S.fx=S.fx.filter(p=>p.life>0)}
function bg(){const w=W(),h=H(),split=h*.47;let g=x.createLinearGradient(0,0,0,split);g.addColorStop(0,'#60d6ec');g.addColorStop(1,'#8de5ef');x.fillStyle=g;x.fillRect(0,0,w,split);x.fillStyle='#f0f1f3';x.fillRect(0,split,w,h-split);x.globalAlpha=.18;x.fillStyle='#fff';for(let i=0;i<14;i++){x.beginPath();x.arc((i*73+S.dragonX*.1)%w,70+(i*41)%(split-90),2+i%3,0,7);x.fill()}x.globalAlpha=1}
function yarnTrack(){const w=W(),h=H(),split=h*.47,segments=Math.max(1,S.yarn),pts=[];for(let i=0;i<=30;i++){const t=i/30,px=45+t*(w-90),py=split*.69+Math.sin(t*5.4)*50;pts.push([px,py])}x.lineCap='round';x.lineJoin='round';x.lineWidth=22;x.strokeStyle='#dce6e9';x.beginPath();pts.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.stroke();for(let i=0;i<segments;i++){const a=pts[Math.floor(i/Math.max(1,S.target)*29)],b=pts[Math.min(30,Math.floor((i+1)/Math.max(1,S.target)*29)+1)];x.strokeStyle=COLORS[i%4];x.lineWidth=18;x.beginPath();x.moveTo(...a);x.lineTo(...b);x.stroke()}x.font='38px serif';x.textAlign='center';x.fillText('🐱',w/2,split*.52);x.font='24px serif';x.fillText('❤️'.repeat(Math.max(0,S.lives)),w/2,split*.39);x.font='29px serif';x.fillText('🎁',w-48,split*.71)}
function dragon(){x.save();x.translate(S.dragonX,77);x.font='64px serif';x.textAlign='center';x.fillText('🐉',0,0);x.restore();x.strokeStyle='#673b2b88';x.lineWidth=4;x.beginPath();x.moveTo(S.dragonX,100);x.lineTo(S.dragonX,H()*.48);x.stroke()}
function roundRect(cx,cy,w,h,r){x.beginPath();x.roundRect(cx-w/2,cy-h/2,w,h,r)}
function block(b){if(b.dead)return;const sh=b.shake?Math.sin(b.shake*65)*6:0;x.save();x.translate(sh,0);x.shadowColor='#0004';x.shadowBlur=5;x.shadowOffsetY=3;roundRect(b.x,b.y,b.w,b.h,7);let g=x.createLinearGradient(0,b.y-b.h/2,0,b.y+b.h/2);g.addColorStop(0,COLORS[b.color]);g.addColorStop(1,DARK[b.color]);x.fillStyle=b.locked?'#25282d':g;x.fill();x.lineWidth=2;x.strokeStyle='#fff8';x.stroke();x.shadowColor='transparent';x.fillStyle='#fff';x.font='bold 24px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(b.locked?'🔒'+Math.max(0,b.need):DIRS[b.dir].ch,b.x,b.y+1);x.restore()}
function cannon(){const px=W()/2,py=H()*.46;x.save();x.translate(px,py);x.fillStyle='#444a5b';roundRect(0,0,44,44,9);x.fill();x.fillStyle='#697286';x.fillRect(-8,-31,16,34);x.fillStyle='#ffd33d';x.beginPath();x.arc(0,-34,9,0,7);x.fill();x.restore()}
function draw(){x.clearRect(0,0,W(),H());bg();yarnTrack();dragon();cannon();for(const b of S.blocks)block(b);for(const s of S.shots){x.strokeStyle='#ffffffbb';x.lineWidth=3;x.beginPath();x.moveTo(W()/2,H()*.46);x.lineTo(s.x,s.y);x.stroke();x.fillStyle=COLORS[s.color];x.beginPath();x.arc(s.x,s.y,9,0,7);x.fill()}for(const p of S.fx){x.globalAlpha=Math.max(0,p.life);x.fillStyle=p.col;x.fillRect(p.x,p.y,5,5)}x.globalAlpha=1;x.fillStyle='#536a78';x.font='bold 13px system-ui';x.textAlign='left';x.fillText('Ziel: '+S.cleared+'/'+S.target,12,H()-10);x.textAlign='right';x.fillText('Drache in '+Math.ceil(S.dragonDrop)+'s',W()-12,H()-10)}
function loop(t){const dt=Math.min(.034,(t-S.last)/1000);S.last=t;update(dt);draw();requestAnimationFrame(loop)}
function pos(e){const r=c.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
c.addEventListener('pointerdown',e=>{e.preventDefault();const p=pos(e);const hit=S.blocks.filter(b=>!b.dead&&Math.abs(p.x-b.x)<b.w*.65&&Math.abs(p.y-b.y)<b.h*.7).sort((a,b)=>Math.hypot(p.x-a.x,p.y-a.y)-Math.hypot(p.x-b.x,p.y-b.y))[0];if(hit)shootBlock(hit)});
$('#hammer').onclick=()=>{if(!S.running||S.hammer<=0)return;const b=S.blocks.filter(b=>!b.dead).sort((a,b)=>b.y-a.y)[0];if(b){S.hammer--;shootBlock(b,true);hud()}};
$('#shuffle').onclick=()=>{if(!S.running||S.shuffle<=0)return;S.shuffle--;const alive=S.blocks.filter(b=>!b.dead);const places=alive.map(b=>[b.x,b.y]).sort(()=>Math.random()-.5);alive.forEach((b,i)=>{b.x=places[i][0];b.y=places[i][1];b.dir=rand(4)});hud();toast('Steine gemischt')};
$('#rainbow').onclick=()=>{if(!S.running||S.rainbow<=0)return;S.rainbow--;for(let i=0;i<4;i++){const b=S.blocks.find(b=>!b.dead&&b.color===i);if(b)shootBlock(b,true)}hud()};
$('#speed').onclick=()=>{S.speed=S.speed===1?2:1;$('#speed').textContent='⏩ x'+S.speed};
$('#settings').onclick=()=>{S.running=false;show('Spielanleitung',`<div class="help"><p><b>Ziel:</b> Befreie die Katze, indem du die farbigen Garnsegmente entfernst.</p><p>Tippe einen Pfeilstein an. Er kann nur abgeschossen werden, wenn sein Pfeilweg frei ist. Der Drache wirft regelmäßig neue Steine ab.</p><p>Volle Farbspulen müssen durch andere Farben entlastet werden. Schwarze Steine entsperren sich nach weiteren Treffern.</p><p>🔨 zerstört einen Stein, 🔀 mischt das Feld, 🌈 entfernt bis zu vier Farben.</p></div><button class="action" id="restart">Level neu starten</button>`)};
$('#close').onclick=()=>{hide();S.running=true};document.addEventListener('click',e=>{if(e.target.id==='restart')reset();if(e.target.id==='next'){S.level++;localStorage.dyr_level=S.level;reset()}if(e.target.id==='retry')reset()});
function show(t,b){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modal').classList.remove('hidden')}function hide(){$('#modal').classList.add('hidden')}
function win(){S.running=false;localStorage.dyr_level=S.level+1;show('Level geschafft!',`<div class="big">🎉🐱🐉</div><p>Die Katze ist gerettet.</p><button class="action" id="next">Nächstes Level</button>`)}function lose(){S.running=false;show('Level verloren',`<div class="big">💥</div><p>Der Drache hat das Feld überfüllt.</p><button class="action" id="retry">Noch einmal</button>`)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});resize();reset();requestAnimationFrame(t=>{S.last=t;requestAnimationFrame(loop)});
